### ISSUE TITLE
Travis CI failing on compiling our repo

### ISSUE THREAD

**Issue by lulak21** [Knowledge21/awesome-agile#19]
Travis CI is always trying to compile our repo. Once we are not (yet) a code repo, we have no reason to see it failing every push we make.

Please help removing Travis from this repo for now... :)

**Comment by thebigtoona** [comment]
Maybe this helps? I don't know a lot about Travis but it kind of looks like its account integrated. 

https://stackoverflow.com/questions/30874853/how-do-you-remove-a-github-repository-for-travis-ci-tests

**Comment by ayr-ton** [comment]
The CI is for checking the links.
So an option would be fixing the CI behavior to check the links correctly.

Will make a PR removing the CI for now and then we could open a new issue if fits.
